apps/front/forms.py
from wtforms import Form,StringField,IntegerField,ValidationError
from wtforms.validators import Regexp, EqualTo, Length,InputRequired
from utils.memcached import mc
from .models import Front_user
from apps.models import PostModel
from flask import g

class Regist_verify(Form):              #注册表单验证
    ''' 用户名长度为2到20位
        密码要求最少6位最大20位，只能是数字字母下划线
        手机号码满足标准格式，且不能和数据库重复
        验证码格式4位，和memcache的验证码一致
        图片验证码要求4位，不区分大小写，和memcached的验证码一致
    '''
    username=StringField(validators=[Regexp(r'.{2,20}',message='用户名输入不正确')])
    passwd=StringField(validators=[Regexp(r"\w{6,20}",message='密码输入格式不正确')])
    repasswd=StringField(validators=[EqualTo('passwd',message='两次密码输入不一致')])
    mobile=StringField(validators=[Regexp(r'1[34578]\d{9}',message='手机号码输入错误')])
    verifycode=StringField(validators=[Regexp(r'\d{4}',message='验证码输入错误')])
    imgverifycode=StringField(validators=[Regexp(r"\w{4}",message='验证码最多4位')])
    '''自定义手机验证码验证'''
    def validate_mobile(self,field):
        mobile=field.data
        user=Front_user.query.filter_by(telephone=mobile).first()
        if user:
            raise  ValidationError(message='您已注册，请勿重新注册')
    '''自定义短信验证码验证'''
    def validate_verifycode(self,field):
        mobile=self.mobile.data
        code=mc.get(mobile)             #从memcached中取出这个手机号码对应的验证码
        print(code)
        print(type(code))
        if not code or code!=field.data:
            raise ValidationError(message='手机验证码错误')
    '''自定义图片验证码验证'''
    def validate_imgverifycode(self,field):
        data=field.data.lower()
        code=mc.get(data)   #从图片中取出验证码
        if not code or code!=data:
            raise ValidationError('图片验证码错误')




class Login_verify(Form):                                                   # 登录验证
    mobile=StringField(validators=[Regexp(r'1[3578]\d{9}',message='手机号码输入错误')])
    passwd=StringField(validators=[Regexp(r'.{6,20}')])

    def validate_mobile(self,field):
        mobile=field.data
        passwd=self.passwd.data
        user=Front_user.query.filter_by(telephone=mobile).first()
        if not user:
            raise ValidationError('没有这个用户，请注册')
        if not user.check_passwd(passwd):
            raise ValidationError('用户密码错误')

class Post_verify(Form):                                                     #用户发帖验证
    title=StringField(validators=[InputRequired(message='请输入标题')])
    content=StringField(validators=[InputRequired(message='请输入文章内容')])
    id=IntegerField(validators=[InputRequired(message='请选择板块')])
    img_code=StringField(validators=[Regexp(r'\w{4}',message='验证码格式不正确')])
    def validate_img_code(self,field):
        img_code=field.data.lower()
        code=mc.get(img_code)
        if not code or code!=img_code:
            raise ValidationError('验证码不正确')


class Acommen_verify(Form):                                                 #添加评论验证
    post_id=IntegerField(validators=[InputRequired(message='你评论的帖子不存在')])
    content=StringField(validators=[InputRequired(message='请输入评论内容哦！')])
    def validate_article_id(self,field):
        post=PostModel.query.filter_by(id=field.article_id).first
        if not post:
            raise ValidationError('您评论的帖子不存在哟')


class upUser_verify(Form):                                                  #修改用户基本信息
    username=StringField(validators=[Regexp(r'.{2,16}',message='用户名格式不正确')])
    avatar=StringField(validators=[InputRequired('请选择您的头像')])
    intr=StringField(validators=[InputRequired('简介信息不能为空哦')])



class resetpassword_Veriyf(Form):
    password = StringField(validators=[Regexp('[a-z0-9]{6,16}', message='密码为6到16位，字母数字下下划线')])
    password1 = StringField(validators=[EqualTo("password", message='2次密码不一致')])
    code = StringField(validators=[Regexp(r'\d{4}', message='验证码输入错误')])

    '''自定义短信验证码验证'''
    def validate_code(self, field):
        mobile =g.front_user.telephone
        code = mc.get(mobile)  # 从memcached中取出这个手机号码对应的验证码
        print(code)
        print(type(code))
        if not code or code != field.data:
            raise ValidationError(message='手机验证码错误')

apps/common/views.py
from flask import Blueprint,request,jsonify, make_response,g
from flask_mail import Message
from exts import mail
from utils.miaodi.miaodi_sms_regist import sendRegistMessage
from random import randrange
from utils.captcha import ValidCodeImg
from io import BytesIO
from .forms import mobile_verify,resetpasswd_verify
from apps.front.decorators import request_login
from utils.memcached import mc
import qiniu
bp=Blueprint('common',__name__,url_prefix='/common')
@bp.route('/')
def index():
    return 'common'


'''错误代码500；服务器异常  200 成功   错误代码400： 没有输入邮箱账号'''
@bp.route('/send_email_code/',methods=['GET'])                                          #发送邮箱验证码验证
def send_email_code():
    email=request.args.get('email')     #获取get方式发送过来的email
    if not email:           #如果没有输入email
        return jsonify({'code':400,'message':'请输入您的邮箱账号'})
    code = randrange(1000, 9999)    #生成一个随机的四位数的验证码
    code=str(code)
    message=Message('网络邮箱验证',recipients=[email],body='您正在修改您的默认邮箱：验证码为'+code+',验证码的有效时间是10分钟。[小杨科技]') #编辑短信内容
    try:
        mail.send(message)     #发送信息
        print(message)       #打印一下验证码，方便调试
        mc.set(email,code,time=600)          #把邮箱和验证码绑定在一起存放在memcached里面，过期时间是10分钟
        return jsonify({'code': 200, 'message': '发送成功'})
    except:
        return jsonify({'code':500,'message':'网络异常' })




'''200：发送成功，
code 403(表单验证失败,返回具体验证信息)
code 404(未输入)
'''
@bp.route('/send_message/',methods=['GET','POST'])          #发送注册短信验证码
def send_message():
    '''
    :param:mobile
    :return:
    '''
    if request.method=='POST':
        form=mobile_verify(request.form)
        if form.validate():
            code = randrange(1000, 9999)
            code=str(code)
            mobile=form.mobile.data
            smsContent = '【飞讯社区】您的验证码为{0}，请于5分钟内正确输入，如非本人操作，请忽略此短信。'.format(code)
            sendRegistMessage(mobile, smsContent)
            mc.set(mobile,code,300)    #把验证码存放在memcached里面,过期时间为5分钟
            print('{0}的验证码为{1}'.format(mobile,code))
            return  jsonify({'code':200,'message':'发送成功'})
        else:
            message=form.errors.popitem()[1][0]
            return jsonify({'code':403,'message':message})









@bp.route('/refreshcode/')        #刷新验证码
def refreshcode():
    imgcode=ValidCodeImg()
    data,valid_str=imgcode.getValidCodeImg()   #获取随机生成的图片和验证码
    out=BytesIO()       #创建一个ByteIo对象
    out.write(data) #把图片保存到out中
    out.seek(0)   #把光标指向最开始
    resp=make_response(out.read())   #把图片从Byteio中读出来
    resp.content_type='image/png'    #设置图片的格式
    valid_str=valid_str.lower()
    mc.set(valid_str,valid_str.lower(),time=300)     #把图形验证码存放在Mecached里面，设置图形验证码的过期时间为5分钟
    return resp


@bp.route('/uptoken/')         #qiniu云官方提供的接口
def uptoken():
    access_key = 'H23yW6b9whf42VT-eCaTxc4mHeRrOIhPtTbA1KNX'
    secret_key = 'teaFq7bSuo7oq3Sh_zy8aJR80H1xk0CPmJ8N3net'
    q = qiniu.Auth(access_key,secret_key)
    bucket = 'boards'
    token = q.upload_token(bucket)
    return jsonify({"uptoken":token})

apps/front/__init__.py
import apps.front.hooks

apps/front/views.py
from flask import (
                   Blueprint,
                   render_template,
                   request,
                   jsonify,
                   views,
                   session,
                   g,
                   abort
                   )
from .forms import (
                    Regist_verify,
                    Login_verify,
                    Post_verify,
                    Acommen_verify,
                    upUser_verify,
                    resetpassword_Veriyf
                    )
from .models import Front_user
from apps.models import (
                        PostModel,
                        Commen_Model,
                        LikeModel,
                        Banner_Model,
                        BoardModel,
                        FollowModel,
                        PostLikeModel
                        )
from exts import db
from random import randrange
from utils.memcached import mc
from utils.miaodi.miaodi_sms_success import sendSuccessMessage
from utils.miaodi.miaodi_sms_regist import sendRegistMessage
from .decorators import request_login
import config
from flask_paginate import get_page_parameter,Pagination

bp=Blueprint('front',__name__)

@bp.route('/',methods=['GET'])                                                               #首页
def index():
    banners=Banner_Model.query.order_by(Banner_Model.priority.desc()).limit(5)#取出5条banner信息返回给主页，用于主页显示5条轮播图
    boards=BoardModel.query.all()                                              #取出所有板块，给前台显示出来
    goodpost=PostModel.query.filter(PostModel.isgood != None).order_by(PostModel.isgood.desc()).limit(5)#展示十条精品贴
    rposts=PostModel.query.order_by(PostModel.id.desc()).limit(5)            #取出最热的5条帖子
    content={
        'goodpost':goodpost,
        "rposts":rposts,
        'banners':banners,
        'boards':boards
    }
    return render_template('front/front_index.html',**content)



@bp.route('/regist/',methods=['GET','POST'])                                        #注册功能
def regist():
    if request.method=='GET':                                                       #GET方法
        return_to=request.referrer    #如果这个注册页面是通过用户浏览的时候点击进来的，那么获取他第三方来的url，方便注册后跳转到第三方页面
        if return_to and return_to!=request.url:
            return render_template('front/front_regist.html',return_to=return_to)
        else:
            return render_template('front/front_regist.html')
    else:                   #POST方法
        '''
        :param  username,passwd passwd2 telephone img_code
        :return: code 200  成功
                code  412  用户输入的数据不正确，或者已经注册（返回具体错误信息）
        '''
        form=Regist_verify(request.form)
        if form.validate():                 #验证表单
            username=form.username.data
            passwd=form.passwd.data
            telephone=form.mobile.data
            user=Front_user(username=username,passwd=passwd,telephone=telephone)
            db.session.add(user)
            db.session.commit()             #存放数据库，注册完成
            sendSuccessMessage(telephone,'【飞讯社区】尊敬的用户，您已成功注册为本网站会员。')
            return jsonify({'code':200,'message':'注册成功'})

        else:
            message=form.errors.popitem()[1][0]
            return jsonify({'code':412,'message':message})                       #错误代码412，用户输入的数据有问题


'''412表单验证失败，弹出第一条错误信息
    200 成功
'''
class View_login(views.MethodView):                                              #登录接口
    def get(self):
        return_to = request.referrer                                            # 获取他是从哪一个网址跳转过来的
        if return_to and return_to!=request.url:                                #如果他有上一个网址，并且上一个网址不登录他自己，则返回上一个网址
            return render_template('front/front_login.html',return_to=return_to)
        else:#否则则不返还return_to
            return render_template('front/front_login.html')
    def post(self):
        form=Login_verify(request.form)                                        #把数据从表单中取出来进行验证
        if form.validate():                                                    #如果数据验证正确
            mobile = form.mobile.data  # 取出手机号
            user = Front_user.query.filter_by(telephone=mobile).first()  # 从数据库中取出这个用户
            if user.is_delete:
                return jsonify({'code':403,'message':'您的账户已经被拉黑'})
            session[config.FRONT_USER_ID]=user.id   #把用户的id取出来放在session[front_user_id]里面
            return jsonify({'code':200,'message':'登录成功'})
        else:
            message=form.errors.popitem()[1][0]
            return jsonify({'code':412,'message':message})
bp.add_url_rule('/login/',view_func=View_login.as_view('login'))


@bp.route('/front_off/',methods=['POST'])                                       #注销登录
def front_off():
    del session[config.FRONT_USER_ID]
    return jsonify({'code':200,'message':'成功注销登录'})

'''code 200   成功发表文章
   code 400   不存在该板块
   code 403(表单验证失败，用户输入信息格式不正确)
  '''

@bp.route('/apost/',methods=['GET','POST'])                                     #添加文章
@request_login
def apost():
    '''
        post:
               :param :文章的标题（title） 板块的id(id) 图片验证码（img_code） 文章内容（content）
               :return: code 200   json  发布成功
                        code 400   json  不存在该板块
                        code 403   json  传过来的数据有问题
     '''
    if request.method=='GET':
        boards=BoardModel.query.all()
        content={
            'boards':boards
        }
        return render_template('front/front_apost.html',**content)
    else:
        form=Post_verify(request.form)
        id=form.id.data
        title=form.title.data
        content=form.content.data
        if form.validate():
            board=BoardModel.query.get(id)
            if board:
                post=PostModel(title=title,content=content)
                post.board=board
                post.author=g.front_user
                db.session.add(post)
                db.session.commit()
                return jsonify({'code':200,'message':'发布成功'})
            else:
                return jsonify({'code':400,'message':'不存在该板块'})
        else:
            message=form.errors.popitem()[1][0]
            return jsonify({'code':403,"message":message})


@bp.route('/topic/',methods=['GET'])                                        #进入板块
def topic():
    '''
    :param  板块(id)
    :return: 进入板块
    '''
    if request.method=='GET':
        '''
        1.表示按最新排序
        2.按精华帖排序
        3.按点赞最多帖子排序
        '''
        id=request.args.get('id')                                           #获取板块id，拿到具体板块信息
        sort_method=request.args.get('st',default='1')                      #获取排序方式
        board=BoardModel.query.get(id)
        userss=FollowModel.query.filter_by(board_id=board.id,statue=1).all()
        followcount=len(userss)
        user=g.get('front_user')
        if user:                                                    #判断当前用户是否关注了这个板块
            follow=FollowModel.query.filter(FollowModel.user_id==user.id,FollowModel.board_id==board.id).first()
            if follow:
                statue=follow.statue
            else:
                statue=False
        else:
            statue=False
        postcount = PostModel.query.filter_by(board_id=board.id).count()  # 当前板块的所有文章
        page=request.args.get(get_page_parameter(),type=int, default=1)     #获取用户传上来的是第几页
        start=(page-1)*10                                                   #开始位置
        end=start+10                                                        #结束位置
        pagination=Pagination(bs_version=3,page=page, total=PostModel.query.filter_by(board_id=id).count())          #创建分页对象
        print(type(sort_method))
        if sort_method=='1':

            posts = PostModel.query.order_by(PostModel.create_time.desc()).filter_by(board_id=id).slice(start, end)  # 获取帖子从起始位置到结束位置的帖子阶段的帖子
            content = {
                'postcount':postcount,                                      #帖子总数量
                'statue':statue,                                            #收藏状态
                'board': board,                                             #板块对象
                'posts': posts,                                             #该板块所有帖子
                'pagination': pagination,                                   #分页
                'followcount':followcount                                   #该板块关注人数
            }
            return render_template('front/front_board.html', **content)
        elif sort_method=='2':
            print(123)
            posts = PostModel.query.order_by(PostModel.isgood.desc(),PostModel.create_time.desc()).filter_by(board_id=id).slice(start, end)  # 获取帖子从起始位置到结束位置的帖子阶段的帖子
            content = {
                'statue':statue,
                'board': board,
                'posts': posts,
                'pagination': pagination
            }
            return render_template('front/front_board.html', **content)
        else:
            posts=PostModel.query.order_by(PostModel.like_number.desc(),PostModel.create_time.desc()).filter_by(board_id=id).slice(start,end)#按点赞数量排序
            content = {
                'statue': statue,
                'board': board,
                'posts': posts,
                'pagination': pagination
            }
            return render_template('front/front_board.html', **content)

@bp.route('/pdetial/',methods=['GET'])                                      #帖子详情
def pdetial():
    '''
    :param:  帖子的id(id)
    :return: 帖子的详情,
            帖子有问题，跳转到404
    '''
    id=request.args.get('id')                                              #获取用户点击的是哪一篇帖子
    if id:
        post=PostModel.query.filter_by(id=id).first()                      #查找这篇帖子
        id=post.author.id
        recent_post=PostModel.query.filter(PostModel.author_id==id).limit(10)   #获取该帖子主人最近发表的10篇文章
        if post:
            number=PostLikeModel.query.filter_by(post_id=post.id,statue=True).all()
            statue=False
            if session.get(config.FRONT_USER_ID):
                user=g.front_user

templates/front/front_board.html
{% extends 'front/front_index_base.html' %}

{% block title %}
    板块
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_board.css') }}">
    <script src="{{ static('front/js/front_board.js') }}"></script>
{% endblock %}

{% block page_content %}

<div class="row">
    <!--左侧-->
    <div class="col-md-8" style="margin-top: 30px;">
        <div class="title-box">
            <div class="avatar">
                <img src="{{board.img_url }}" alt="">
            </div>
            <div class="title_right">
                <div id="board_title">{{ board.name }}</div>
                <div id="info">收录了 <span>{{ postcount}}</span>篇文章·<span>{{ followcount }}</span>人关注</div>
            </div>
            <a href="{{ url_for('front.apost') }}"><div class="addpost">投稿</div></a>

            {% if statue %}
            <div  id="nofollow" class="noFocus follow" board-id="{{ board.id }}">已关注</div>
            {% else %}
            <div  class="Focus follow" board-id="{{ board.id }}">关注</div>
            {% endif %}

        </div>
        <div class="test"></div>

        <div class="title_select">
            <div class="title_select_inner zx title_select_xanzhong">
                <a class="sort-tag"  href="{{ url_for('front.topic') }}?id={{ board.id }}&st=1">最新帖子</a>
            </div>
            <div class="title_select_inner jh">
                <a class="sort-tag" href="{{ url_for('front.topic') }}?id={{ board.id }}&st=2">精华帖</a>
            </div>
            <div class="title_select_inner rm">
                <a class="sort-tag" href="{{ url_for('front.topic') }}?id={{ board.id }}&st=3">热门帖</a>
            </div>
        </div>


{#    帖子列表#}
<div class="theme">
    <div class="theme_con">
        <ul class="post-list">
            {% for post in posts %}
            <li class="theme_list">
                <!--头像-->
                <div class="theme_list_img">
                    {% if post.author.avatar %}
                    <a href=""><img src="{{ post.author.avatar }}" alt=""></a>
                    {% else %}
                {#使用默认头像#}
                    <a href=""><img src="../../static/front/img/avatar.jpg" alt=""></a>
                    {% endif %}
                </div>
                <!--标题-->
                <div class="theme_list_con">
                    <div class="title">
                        <a class="return_pdetial" post-id="{{ post.id }}" href="{{ url_for('front.pdetial') }}">
                            {{ post.title|truncate(length=15) }}</a>
{# 加精图标#}             {% if post.isgood %}
                        <div id="goodpost">精</div>
                        {% endif%}
                    </div>
                    <!--发布时间-->
                    <div  class="auth_msg">
                        <a href="">{{ post.author.username }}·</a>
                        <span>{{ post.create_time|settime }}·</span>
                        <span>{{ board.name }}</span>
                        <p class="see">
                            <span class="numb">
                                <img src="../../static/front/img/浏览.png" alt="浏览图标">
                                        {{ post.browse }}
                            </span>

                        </p>
                        <p class="see">
                            <span class="numb">
                                <img src="../../static/front/img/点赞%20.png" alt="点赞图标">
                                                    {{ post.like_number }}
                            </span>
                        </p>
                    </div>
                </div>
            </li>
            {% endfor %}
            </ul>
              <div style="text-align: center">{{ pagination.links }}</div>
         </div>
    </div>
</div>




    <!--右侧-->
    <div class="col-md-3 right-board">
        <p class="title">专题公告</p>
        <div class="collection">
            <p>{{ board.notice }}</p>
        </div>
        <br />
        <hr />



        <!--管理员-->
        <div>
            <p class="manager">管理员</p>
            <ul>
                <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                    <span class="tag">创造者</span>
                </li>
                <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>  <li>
                    <a class="author" href="">
                        <img src="" alt="">
                    </a>
                    <a class="name" href="">简书</a>
                </li>

            </ul>
        </div>
    </div>
</div>



{% endblock %}

templates/front/front_index_base.html
{% from 'common/_macros.html'import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    <title>人工智能论坛</title>
    <link rel="stylesheet" href="{{ static('common/style.css')  }}">
    <link rel="stylesheet" href="{{ static('front/css/reset.css') }}">
    <link rel="stylesheet" href="{{ static("front/css/front_index_base.css") }}">
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <link rel="stylesheet" href="{{ static("front/css/front_index_base.css") }}">
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css') }}">
    <script src="{{ static('front/js/front_index_base.js') }}"></script>
    <script src="{{ static('common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ static('common/sweetalert/xtalert.js') }}"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
{#头部分开始#}
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
<nav>
        <div class="width-limit">
            <div id="mainlogo">
                <a class="logo" href="#"><img src="http://s1.bbs.xiaomi.cn/statics/images/logo_cn.png" alt="logo" id="main-logo"></a>
            </div>
            <div id="menu" class="w">
                <!--版心左侧-->
                <div id="menu_child">
                    <ul>
                        <li>
                            <a href="{{ url_for('front.index') }}" id="index">首页</a>
                        </li>
                        <li>
                           <a href="{{ url_for('front.index') }}" id="board">板块</a>
                        </li>
                        <li id="search_box">
                            <form id="search_form" action="" method="post">
                                <input id="search" type="text">
                                <a id="search_btn" href="{{ '/search/' }}"><i id="fdj"></i></a>
                            </form>
                        </li>
                    </ul>
                </div>
                <!--版心右侧-->
                <div class="login-box">
                    {% if not g.front_user %}
                    <a id="login" href="{{ url_for('front.login') }}">登录</a>
                    {% endif %}
                </div>
            </div>
            <div class="nav-inner-right">
                <a id="writing" href="{{ url_for('front.apost') }}">发帖</a>
                {% if g.front_user %}
                    <a href="" id="personal-go"><img src="{{ g.front_user.avatar }}" alt=""></a>
                {% else %}
                <a id="regist" href="{{ url_for('front.regist') }}">注册</a>
                {% endif %}
            </div>
        </div>
    </nav>
<div class="left-tag">
        <div class="f-left-nav">
        <span id="close"></span>
        <div class="f-left-nav-header">
            切换板块
        </div>
        <div class="f-left-nav-content">
            <div class="f-left-nav-title">
                技术专区
            </div>
            <ul class="board-list-tag">
                {% for board in g.boards %}
                <li><a href="{{ "/topic/" }}" board-id="{{ board.id }}">{{ board.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% block page_banner %}

{% endblock %}
{#头结束#}
<div class="container" >
    {% block page_content %}

    {% endblock %}
</div>
{% if g.front_user %}
  <ul class="dropdown-user">
                    <li><a href="{{ url_for('front.personal') }}?user-id={{ g.front_user.id }}"><i></i><span>个人设置</span></a></li>

      <li><a href="" id="front_off"><i></i><span>退出</span></a></li>
                </ul>
{% endif %}
{% block footer %}

{% endblock %}

</body>
</html>

templates/front/front_login.html
{% from'common/_macros.html'import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
    <link rel="stylesheet" href="{{ static("front/css/front_login.css") }}">
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <script src="{{ static('common/sweetalert/sweetalert.min.js')}}"></script>
    <script src="{{ static('common/sweetalert/xtalert.js') }}"></script>
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css') }}">
    <script src="{{ static('front/js/front_login.js') }}"></script>
</head>
<body>
<nav>
    <div class="nav_bar w">
        <div id="logo"><a href="{{ url_for('front.index') }}"><img src="../../static/front/img/login_logo.png" alt=""></a></div>
    </div>

    <div class="panel">
        <div class="panel_inner w">
            <!--登录页面-->
              <div class="login_main">
                      <div class="form_head">
                          <a href="" id="mobile_login">手机登录</a>
                      </div>
                  <form action="" method="post">
                        <div class="login_mobile">
                            <input type="text" placeholder="请输入手机号码" name="mobile">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        </div>
                        <div class="login_passwd">
                            <input type="password" placeholder="请输入密码" name="passwd">
                        </div>
                        <div class="subs">
                            <input id="sub-btn" type="submit" value="登录">
                        </div>
                  </form>
                        <div class="second_login">
                                 <div class="login_img_head">
                                     <img src="../../static/front/img/login_second_login.png" alt="">
                                 </div>
                        </div>
              </div>
        </div>
    </div>
</nav>
{#    存放数据是从哪个url点击进入注册页面的url#}
    <span style="display: none;" id="return_to_span">{{ return_to }}</span>

</body>
</html>