apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash

class Permission(object):     #权限模型
    #1. 255用二进制表示为11111111，表示最高权限
    ALL_PERMISSION= 0b11111111
    #2. 访客权限
    VISITOR=        0b00000001
    #3.  管理帖子
    POSTER=         0b00000010
    #4.  管理评论的权限
    COMMENTER=      0b00000100
    #5.  管理板块的权限
    BOARDER=        0b00001000
    #6.   管理前台用户的权限
    FRONTUSER=      0b00010000



# 创建cmsuser和cms_role的中间表
cms_user_role=db.Table('cms_user_role',
                       db.Column('cms_role_id',db.Integer,db.ForeignKey('cms_role.id'),primary_key=True),
                       db.Column('cms_user_id',db.Integer,db.ForeignKey('cms_user.id'),primary_key=True)
                       )

class CMS_role(db.Model):                   #角色表
    __tablename__='cms_role'
    id=db.Column(db.Integer,primary_key=True,autoincrement=True)
    name=db.Column(db.String(20),nullable=False)            #名称
    desc=db.Column(db.String(255),nullable=False)           #简介
    role_permission=db.Column(db.Integer,default=Permission.VISITOR)    #角色权限
    create_time=db.Column(db.DateTime,default=datetime.now())           #建立时间

    users=db.relationship('CMS_user',secondary=cms_user_role,backref='roles')    #和CMS表建立多对多的关系

class CMS_user(db.Model):     #创建一个CMS用户类（用户名，密码，email,连接时间）
    __tablename__='cms_user'
    id=db.Column(db.Integer,primary_key=True,autoincrement=True)
    username=db.Column(db.String(20),nullable=False)
    _passwd=db.Column(db.String(255),nullable=False)       #密码这种字段必须在数据库中是加密的，这样能防止黑客进攻，密码泄露
    email=db.Column(db.String(20),nullable=False,unique=True)
    join_time=db.Column(db.DateTime,nullable=False,default=datetime.now())
    def __init__(self,username,passwd,email):           #重写了类初始变量，使其直接输入的时候通过passwd可以修改私有变量_passwd
        self.username=username
        self.passwd=passwd
        self.email=email


    @property
    def passwd(self):
        return self._passwd
    @passwd.setter      #对存放数据库的密码进行加密
    def passwd(self,raw_passwd):
        self._passwd=generate_password_hash(raw_passwd)

    def check_password(self,raw_passwd):
        result=check_password_hash(self.passwd,raw_passwd)#对输入的密码和数据库密码进行对比
        return result

    @property                                                   #获取该用户的所有权限
    def permission(self):
        all_permission=0
        if  not(self.roles):                                    #如果这个用户角色
            return 0
        else:
            for role in self.roles:                             #遍历里面的角色
                all_permission|=role.role_permission            #把里面角色进行或运算
            return  all_permission                              #得到最高权限返回


    def has_permission(self,permissions):                        #查看用户是否有某个权限
        return (self.permission & permissions) ==permissions
        #把用户的权限和需要的权限对比，如果返回的和他本身相等，则用户有这个权限

apps/cms/forms.py
from wtforms import Form,StringField,IntegerField
from wtforms.validators import Length,Email,InputRequired,EqualTo,ValidationError,Regexp
from apps.models import PostModel,Commen_Model
from .models import CMS_user
from utils.memcached import mc
from flask import g

class Cms_login_verify(Form):               #CMS登录验证
    email=StringField(validators=[InputRequired(message='请输入数据'),Email(message='邮箱格式不正确')])  #验证邮箱格式
    passwd=StringField(validators=[InputRequired(message="请输入密码"),Length(6,12,message='密码长度不够')])#密码长度必须为6到12位
    remember=IntegerField(validators=[])


class Cms_resetpwd_verify(Form):
    oldpasswd=StringField(validators=[Length(6,20,message='密码长度不够,请重新输入密码')])
    newpasswd=StringField(validators=[Length(6,20,message='密码长度不够,请重新输入密码')])
    renewpasswd=StringField(validators=[EqualTo("newpasswd",message='两次输入不相同')])


class Cms_resetemail_verify(Form):          #邮箱验证码格式验证
    email=StringField(validators=[Email(message='请输入正确的邮箱')])
    email_code=StringField(validators=[Length(4,4,message="请输入正确格式的验证码")])

    def validate_email_code(self,field):    #如果用户名和密码都满足
        code=mc.get(self.email.data)        #从memcached中取用户名为email值得这个数
        if not code or field.data!=code:    #判断用户输入的邮箱号和验证码是否和先前获取的存放在mecached里面的一样，判断是否取得到
            raise ValidationError('邮箱或者验证码错误')
    def validate_email(self,field):
        email=g.cms_user.email
        if field.data==email:               #如果用户输入的邮箱的邮件名称和原来的邮箱一样
            raise ValidationError('您的邮箱和原始邮箱不能同名')

class Add_banner_verify(Form):               #添加banner图验证
    name=StringField(validators=[InputRequired(message='请输入Banner名称')])
    img_url=StringField(validators=[InputRequired(message='请输入图片链接地址')])
    link_url=StringField(validators=[InputRequired(message='请输入图片跳转地址')])
    priority=IntegerField(validators=[InputRequired(message='请输入优先级')])

class Update_banner_verify(Add_banner_verify):#更新banner图验证
    id=IntegerField(validators=[InputRequired()])


class Add_boarder_verify(Form):                          #添加板块验证
    name=StringField(validators=[InputRequired(message='请输入板块名称')])
    img_url=StringField(validators=[InputRequired(message='请输入图片链接地址')])
    intr=StringField(validators=[InputRequired(message='请输入板块简介')])
    notice=StringField(validators=[InputRequired(message='请输入公告信息')])

class Update_boarder_verify(Add_boarder_verify):        #修改板块验证
    id=IntegerField(validators=[InputRequired(message='获取板块ID错误')])

class Agoodpost_verify(Form):                           #设置帖子为精品贴验证
    id=IntegerField(validators=[InputRequired(message='帖子不存在')])
    def validate_id(self,field):
        id=field.data
        post=PostModel.query.filter_by(id=id).first()  #查找数据库中是否有这篇帖子
        if not post:
            raise ValidationError(message='该帖子不存在')

class Delgoodpost_verify(Form):                         #取消设置帖子为精品贴验证
    id=IntegerField(validators=[InputRequired(message='帖子不存在')])
    def validate_id(self,field):
        id=field.data
        post=PostModel.query.filter_by(id=id).first()  #查找数据库中是否有这篇帖子
        if not post:
            raise ValidationError(message='该帖子不存在')

class Delpost_verify(Form):                           #删除帖子
    id=IntegerField(validators=[InputRequired(message='帖子不存在')])
    def validate_id(self,field):
        id=field.data
        post=PostModel.query.filter_by(id=id).first()  #查找数据库中是否有这篇帖子
        if not post:
            raise ValidationError(message='该帖子不存在')


class aCmsUser_Verify(Form):                            #创建cms_user验证
    username=StringField(validators=[Length(min=2,max=16,message='密码长度为2到16位')])
    password=StringField(validators=[Regexp('[a-z0-9]{6,16}',message='密码为6到16位，字母数字下下划线')])
    password1=StringField(validators=[EqualTo("password",message='2次密码不一致')])
    email=StringField(validators=[Email(message='邮箱格式不正确')])
    def validate_email(self,field):
        user=CMS_user.query.filter_by(email=field.data).first()
        if user:
            raise ValidationError(message='邮箱已注册')


class setPermission_Verify(Form):                     #设置后天权限验证
    user_id=IntegerField(InputRequired(message='用户传参错误'))
    role_id=IntegerField(InputRequired(message='角色传参错误'))
    set=IntegerField(InputRequired(message='修改类型不能为空'))


class DelCommen_Verify(Form):                           #删除帖子
    id=IntegerField(validators=[InputRequired(message='传参错误')])
    def validate_id(self,field):
        id=field.data
        commen=Commen_Model.query.filter_by(id=id).first()  #查找数据库中是否有这篇帖子
        if not commen:
            raise ValidationError(message='该帖子不存在')

apps/cms/__init__.py
import apps.cms.hooks

apps/cms/views.py
from flask import (
                   Blueprint,
                   request,
                   render_template,
                   session,
                   redirect,
                   url_for,
                   g,views,
                   jsonify,
                   abort
                   )
from apps.cms.forms import (
                            Cms_login_verify,
                            Cms_resetpwd_verify,
                            Cms_resetemail_verify,
                            Add_banner_verify,
                            Update_banner_verify,
                            Add_boarder_verify,
                            Update_boarder_verify,
                            Agoodpost_verify,
                            Delgoodpost_verify,
                            Delpost_verify,
                            aCmsUser_Verify,
                            setPermission_Verify,
                            DelCommen_Verify
                            )
from exts import db
from utils.pymysql.pymysqldemo import *
from apps.cms.decorators import Request_login,Request_Permission
from apps.cms.models import CMS_user, Permission,CMS_role,cms_user_role
from apps.models import BoardModel,PostModel
from config import CMS_USER_ID
from apps.front.models import Front_user
from apps.models import Banner_Model,Commen_Model
from flask_paginate import get_page_parameter,Pagination
from datetime import datetime

bp=Blueprint('cms',__name__,url_prefix='/cms')  #创建蓝图


@bp.route('/')                              #后台界面首页
@Request_login
def index():
    return render_template("cms/CMS_index.html")

@bp.route('/cms_off/')    #注销登录
@Request_login         #必须登录才能访问
def cms_off():
    del session[CMS_USER_ID]
    return redirect(url_for("cms.login"))



@bp.route('/profile/')                              #个人中心
@Request_login
def profile():
    return render_template("cms/CMS_profile.html")

#基于方法调度的类视图
'''code 200(输入正确，修改密码成功)
   code 400(密码错误，修改密码失败)
   code 403(表单验证失败，用户输入信息格式不正确)
  '''
class ResetPwd_View(views.MethodView):                  #修改密码
    decorators=[Request_login]          #装饰器（必须登录才可访问）
    def _render(self,address):              #把render_template封装成一个方法
        return  render_template(address)
    def get(self):      #使用get请求
        return self._render("cms/CMS_resetpwd.html")
    def post(self):      #使用post请求
        form=Cms_resetpwd_verify(request.form)  #对接收到的数据进行验证，查看数据格式是否合法
        if form.validate():
            oldpasswd=form.oldpasswd.data        #从验证表单中获取到（老新）密码
            newpasswd=form.newpasswd.data
            if g.cms_user.check_password(oldpasswd):    #旧密码等于数据库的密码，验证通过返回成功
                g.cms_user.passwd=newpasswd
                db.session.commit()
                return jsonify({'code':200,'message':''})
            else:
                return jsonify({'code':400,'message':'密码输入错误'})
        else:
            message=form.errors.popitem()[1][0]    #弹出表单验证错误的第一条错误提示
            return jsonify({'code':403,'message':message})
bp.add_url_rule('/resetpwd/',view_func=ResetPwd_View.as_view('resetpwd'))



'''
   code 200（修改密码成功）
   code 400 (验证码和邮箱不匹配)
'''
class Resetemail_View(views.MethodView):                    #重置邮箱
    def get(self):
        return render_template('cms/CMS_resetemail.html')
    def post(self):
        form=Cms_resetemail_verify(request.form)
        if form.validate():
            email=form.email.data
            g.cms_user.email=email
            db.session.commit()
            return jsonify({'code':200,'message':'邮箱修改成功'})
        else:
            message=form.errors.popitem()[1][0]
            return jsonify({'code':400,'message':message})
bp.add_url_rule('/resetemail/',view_func=Resetemail_View.as_view('resetemail'))


@bp.route('/boarder/')                                      #板块管理
@Request_Permission(Permission.BOARDER)
def boarder():
    page=request.args.get('page',default=1)
    page=int(page)
    start=(page-1)*8
    end=(page+8)
    boards=BoardModel.query.order_by(BoardModel.id.desc()).slice(start,end)
    pagination=Pagination(bs_version=3,page=page,total=BoardModel.query.count())
    contents={
        'boards':boards,
        'pagination':pagination
    }
    return render_template('cms/CMS_boarder_manage.html',**contents)


'''code 200(输入正确，修改密码成功)
   code 403(表单验证失败，用户输入信息格式不正确)
  '''
@bp.route('/addboard/',methods=['POST'])            #添加板块
def addboard():
    form=Add_boarder_verify(request.form)          #从接受用户传递过来的参数
    if form.validate():                             #验证用户输入格式是否正确
        img_url=form.img_url.data                   #从验证表单中取到数据
        name=form.name.data
        intr=form.intr.data
        notice=form.notice.data
        board=BoardModel(img_url=img_url,name=name,intr=intr,notice=notice)
        db.session.add(board)
        db.session.commit()
        return jsonify({'code':200,'message':'添加成功'})

    else:
        message=form.errors.popitem()[1][0]
        return jsonify({'code':403,'message':message})

'''
code:200,更改成功
code：402,数据库不存在这个banner
code:403,用户修改的数据不符合要求
'''
@bp.route('/updateboard/',methods=['POST'])                  #更新board表信息
def updateboard():
    form=Update_boarder_verify(request.form)
    if form.validate():
        id=form.id.data
        name=form.name.data
        img_url=form.img_url.data
        intr=form.intr.data
        notice=form.notice.data
        board=BoardModel.query.filter_by(id=id).first()    #从数据库中查找这个表对应的id取出来
        if board:       #如果有这个板块，则修改板块里面的字段值，否则提示没有这个板块
            board.name=name
            board.img_url=img_url
            board.intr=intr
            board.notice=notice
            db.session.commit()
            return jsonify({'code':200,'message':'修改成功'})
        else:
            return jsonify({'code':402,'message':'不存在这个板块'})
    else:
        message=form.errors.popitem()[1][0]
        return jsonify({'code':403,'message':message})

@bp.route('/delboard/',methods=['POST'])                                #删除板块
def delboard():
    id=request.form.get('id')
    board=BoardModel.query.filter_by(id=id).first()
    if board:
        db.session.delete(board)
        db.session.commit()
        return jsonify({'code':200,'message':'删除成功'})
    else:
        return jsonify({'code':403,'message':'不存在这个板块'})




@bp.route('/post/')                                                      #帖子管理
@Request_Permission(Permission.POSTER)
def post():
    page = request.args.get(get_page_parameter(), type=int, default=1)  # 获取用户传上来的是第几页
    start=(page-1)*9                                                    #起始位置
    end=start+9                                                         #结束位置
    posts=PostModel.query.all()
    total=len(posts)                                                    #统计总共多少条数据
    pagination=Pagination(bs_version=3,page=page,total=total)
    posts = PostModel.query.slice(start,end)
    content={
        'posts':posts,
        'pagination':pagination
    }
    return render_template('cms/CMS_post_manage.html',**content)


@bp.route('/commen/')                                   #评论管理
@Request_login
@Request_Permission(Permission.COMMENTER)
def commen():
    commens=Commen_Model.query.all()
    return render_template('cms/CMS_commen_manage.html',commens=commens)

@bp.route('/front/',methods=['GET'])                    #前台用户管理
@Request_Permission(Permission.FRONTUSER)
def front():
    users=Front_user.query.all()                        #拿到所有的前台用户
    return render_template('cms/CMS_front_manage.html',users=users)

@bp.route('/cmsuser/',methods=['GET'])                  #后台用户管理
@Request_Permission(Permission.ALL_PERMISSION)
def cmsuser():
    CmsUser=CMS_user.query.all()                        #拿到所有的后台用户
    return  render_template('cms/CMS_cmsuser_manage.html',CmsUser=CmsUser)

@bp.route('/aCmsUser/',methods=['POST'])                #创建CMS用户
def aCmsUser():
    form=aCmsUser_Verify(request.form)
    if form.validate():
        username=form.username.data
        password=form.password.data
        email=form.email.data
        cms=CMS_user(username=username,passwd=password,email=email)
        db.session.add(cms)
        db.session.commit()
        return jsonify({'code':200,'message':'创建用户成功'})
    else:
        message=form.errors.popitem()[1][0]             #表单验证的第一条出错信息
        return jsonify({'code':401,'message':message})

@bp.route('/setCms/',methods=['GET'])                                    #设置用户权限界面
def setCms():
    cms_id=request.args.get("cms_id")
    if cms_id:
        user=CMS_user.query.get(cms_id)
        roles=user.roles
        kfz=False
        jyz=False
        yk=False
        gly=False
        for role in roles:
            if role.name=='开发者':
                kfz=True
            elif role.name=='经营者':
                jyz=True
            elif role.name=='游客':
                yk=True
            elif role.name=='管理员':
                gly=True
        content={
            'user':user,
            'kfz':kfz,
            'jyz':jyz,
            'yk':yk,
            'gly':gly
        }
        return render_template('cms/CMS_set_cmsUser.html',**content)
    else:
        return abort(404)


@bp.route('/addbanner/',methods=['POST'])               #添加轮播图
@Request_login
def addbanner():
    form=Add_banner_verify(request.form)                #从后台获取到前台传入的数据其中包括名称，图片地址，跳转地址和优先级，放入表单中进行验证
    if form.validate():                                 #如果验证成功
        name=form.name.data
        img_url=form.img_url.data
        link_url=form.link_url.data
        priority=form.priority.data
        banner=Banner_Model(name=name,img_url=img_url,link_url=link_url,priority=priority)
        db.session.add(banner)                          #把数据存放到数据库
        db.session.commit()
        return jsonify({'code':200,'message':'添加成功'})
    else:
        message=form.errors.popitem()[1][0]             #弹出表单的第一条验证失败的错误信息
        return  jsonify({'code':403,'message':message})


'''
code:200,更改成功
code：402,数据库不存在这个banner
code:403,用户修改的数据不符合要求
'''

templates/cms/CMS_banner_manage.html
{% extends 'cms/CMS_index_base.html' %}
{% from './common/_macros.html' import static %}
{% block title %}
轮播图管理
{% endblock %}
{% block head %}
    <script src="{{ static('cms/js/cms_banner.js') }}"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ static('common/lqiniu.js') }}"></script>
{% endblock %}
{% block page_title %}
    {{ self.title() }}
{% endblock %}
{% block main_content %}


    {#    添加轮播图按钮#}
    <div class="row">
    <div class="col-md-1 col-md-offset-11">
        <button class="btn btn-warning" data-toggle="modal" style="margin-left: -11px" data-target="#banner_dialog"> 添加轮播图</button>
    </div>
</div>
{#    添加轮播图按钮结束#}


{#    轮播图列表#}
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered">
            <tr>
                <th>轮播图名称</th>
                <th>图片链接地址</th>
                <th>图片跳转地址</th>
                <th>创建时间</th>
                <th>优先级</th>
                <th>操作</th>
            </tr>
                    {#遍历输出banner里面的参数#}
            {% for banner in banners %}
                    {#把banner里面的信息获取到tr里面的属性，为了后期对banner的信息进行管理使用#}
            <tr data-name='{{ banner.name }}' data-img={{ banner.img_url }} data-link={{ banner.link_url }} data-priority={{ banner.priority }}  data-id={{ banner.id }}>
                <td>{{ banner.name }}</td>
                <td><a href="{{ banner.img_url }}" target='_blank'>{{ banner.img_url }}</a></td>
                <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                <td>{{ banner.create_time }}</td>
                <td>{{ banner.priority }}</td>
                <td>
                    <button class="btn-success btn edit_banner_btn"
                            data-toggle="modal" data-target="#banner_dialog">编辑</button>
                    <button class="btn btn-danger del-banner">删除</button>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{#轮播图列表结束#}



{#    banner弹出框#}
    <!-- Modal -->
<div class="modal fade" id="banner_dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <!--inner-->
                <form class="form-horizontal">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" types="123">
                    <!--名称-->
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">名称</label>
                        <div class="col-sm-10">
                            <input type="text" name="name" class="form-control" id="inputEmail3" placeholder="轮播图名称">
                        </div>
                    </div>

                    <!--图片-->
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">图片</label>
                        <div class="col-sm-8 ">
                            <input type="text" name="img_url" class="form-control" id="inputPassword3" placeholder="轮播图图片">
                        </div>
                        <div class="col-sm-2">
                            <button id="select_img" class="btn btn-success" style="border-radius: 18px;margin-left: -12px" >选择图片</button>
                        </div>
                    </div>

                    <!--跳转-->
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">跳转</label>
                        <div class="col-sm-10">
                            <input type="text" name="link_url" class="form-control" id="inputPassword4" placeholder="跳转链接">
                        </div>
                    </div>
                    <!--权重-->
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">优先级</label>
                        <div class="col-sm-10">
                            <input type="text" name="priority" class="form-control" id="inputPassword5" placeholder="优先级">
                        </div>
                    </div>
                     <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button id="submit-btn" type="button" class="btn btn-primary">保存</button>
            </div>
                </form>
            </div>
        </div>
    </div>
</div>
     <!--banner弹出框结束-->
{% endblock %}

templates/cms/CMS_commen_manage.html
{% extends 'cms/CMS_index_base.html' %}
{% block title %}
评论管理
{% endblock %}
{% block page_title %}
    {{ self.title() }}
{% endblock %}
{% block head %}
<script src="{{ static('cms/js/CMS_commen_manage.js') }}"></script>
{% endblock %}
{% block main_content %}
<table class="table table-bordered">
    <tr>
        <th>文章名称</th>
        <th>评论人</th>
        <th>评论内容</th>
        <th>操作</th>
    </tr>
{#遍历输出所有的帖子#}
    {% for commen in commens %}
{#方便对帖子进行加精删除#}
    <tr data-post-id="{{ commen.id }}">
        <td>{{ commen.post.title }}</td>
        <td>{{ commen.author.username }}</td>
        <td>{{ commen.content}}</td>
        <td>
            <button id="delcommen" class="btn btn-danger delpost" cm-id="{{ commen.id }}">删除</button>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/cms/CMS_index.html
{% extends "cms/CMS_index_base.html" %}
{% block title %}
CMS后台管理系统
{% endblock %}
{% block page_title %}
欢迎来到CMS后台管理系统
{% endblock %}

templates/cms/CMS_index_base.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}{% endblock %} </title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static("cms/css/cms_base.css") }}">
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css') }}">
    <script src="{{ static('common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ static('common/sweetalert/xtalert.js') }}"></script>
    <script src="{{ static("cms/js/cms_base.js") }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for("cms.cms_off") }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control"  id="content_post" placeholder="查找帖子...">
              <a href="/cms/searchpost/?content=" id="search_post" class="btn btn-warning">搜索</a>
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for("cms.profile") }}">个人信息</a></li>
                        <li><a href="{{ url_for("cms.resetpwd") }}">修改密码</a></li>
                        <li><a href="{{ url_for("cms.resetemail") }}">修改邮箱</a></li>
                    </ul>
                </li>
                    {% set cms_user=g.cms_user %}
{#              如果用户有帖子管理权限则显示帖子管理#}
                  {% if cms_user.has_permission(Permission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.post') }}">帖子管理</a></li>
                  {% endif %}
{#              如果用户有评论管理权限，则显示评论管理#}
                    {% if cms_user.has_permission(Permission.COMMENTER) %}
                <li class="comments-manage"><a href="{{ url_for('cms.commen') }}">评论管理</a></li>
                    {% endif %}
              {% if cms_user.has_permission(Permission.BOARDER) %}
                <li class="board-manage"><a href="{{ url_for('cms.boarder') }}">板块管理</a></li>
                <li class="banner-manage"><a href="{{ url_for('cms.banner') }}">轮播图管理</a></li>

                {% endif %}
              {% if cms_user.has_permission(Permission.FRONTUSER) %}
                <li class="nav-group user-manage"><a href="{{ url_for('cms.front') }}">前台用户管理</a></li>
              {% endif %}
                  {% if cms_user.has_permission(Permission.ALL_PERMISSION) %}
                <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cmsuser') }}">CMS用户管理</a></li>
                      {% endif %}
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}

            {% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}

                {% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>